# name: Generate pacman animation

# on:
#   schedule: # execute every 12 hours
#     - cron: "*/5 * * * *"

#   workflow_dispatch:

#   push:
#     branches:
#     - main

# jobs:
#   generate:
#     permissions:
#       contents: write
#     runs-on: ubuntu-latest
#     timeout-minutes: 5

#     steps:
#       - name: generate pacman-contribution-graph.svg
#         uses: abozanona/pacman-contribution-graph@main
#         with:
#           github_user_name: ${{ github.repository_owner }}


#       - name: push pacman-contribution-graph.svg to the output branch
#         uses: crazy-max/ghaction-github-pages@v3.1.0
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# name: Generate pacman animation

# on:
#   schedule:
#     - cron: "0 */12 * * *"  # every 12 hours
#   workflow_dispatch:
#   push:
#     branches:
#       - main

# jobs:
#   generate:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#       pages: write

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: generate pacman-contribution-graph.svg
#         uses: abozanona/pacman-contribution-graph@main
#         with:
#           github_user_name: ${{ github.repository_owner }}

#       - name: push pacman-contribution-graph.svg to the output branch
#         uses: crazy-max/ghaction-github-pages@v3.1.0
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Generate pacman animation

on:
  workflow_dispatch:  # Only runs manually when triggered from GitHub UI
    push:
      branches:
        - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
